import type { Metadata } from "next";
import FormEditInvoice from "@/app/components/FormEditInvoice";
import { notFound } from 'next/navigation';
import { fetchSingleInvoice } from "@/app/lib/data";

export const metadata: Metadata = {
  title: "Invoice Gnerator App",
  description: "Generated by adpu.net",
};

type EditInvoiceProps = {
  params: {
    id: number;
  };
};

export default async function EditInvoice({ params }: EditInvoiceProps) {
  const id = params.id;
  const invoice = await fetchSingleInvoice(id);

  if (!invoice) {
    return notFound();
  }

  return (
    <main>
         <FormEditInvoice invoice={invoice} />
    </main>
  );

}