import type { Metadata } from "next";
import FormInvoice from "@/app/components/FormInvoice";

export const metadata: Metadata = {
  title: "Invoice Gnerator App",
  description: "Generated by adpu.net",
};
export default async function CreateInvoice() {
  return (
    <main>
         <FormInvoice  />
    </main>
  );

}